### ISSUE TITLE
Ventilación de los químicos en la sala de almacenaje 

### ISSUE THREAD

**Issue by eak24** [AguaClara/APP_Issue_Tracking#2]
Monroe dije es muy importante para los químicos tener buen ventilación con la afuera y no ventilación con la resto de la planta porque el hipoclorito es muy corrosivo. Tengo dos ideas:
1. Cambiamos los cuartos para que la sala de descansar es ahora la sala de almacenaje y viceversa.
2. Instalamos un ventilador en un tubo de 12" por la sala de descansar para los operadores y guardamos el ventilador en.

**Comment by mintynunez** [comment]
@ethan92429 la bodega para almacenaje de químicos es la que tiene ventana hacia afuera del edificio.
