### ISSUE TITLE
Aislamiento las tanques de acido

### ISSUE THREAD

**Issue by eak24** [AguaClara/APP_Issue_Tracking#3]
Monroe  mencionó que debemos aislar las tanques de acido porque el humo es peligroso. Cualquier ideas para este? Quizás podemos construir un pared con un puerta grande?  Entiendo este es un solución muy caro. Quizás tenemos bastante ventilación con los ventanas en la mesa de químicos.

**Comment by jonschristensen** [comment]
Ya es tarde para redisenar la mesa de quimicos. Creo que, con la concentracion diluida de 10%, las ventanas serán suficientes. Posiblamente pueden agregar un ventilador en una ventana si sea necesario. Podes consultar con el proveedor de quimicos y preguntarles que recomiendan. Ellos nos iban a proveer una capacitación a nosotros y a los operadores, no se si lo hicieron?

**Comment by ghost** [comment]
El acido con concentración de solamente 10% no debe formar demasiado humo,
pero si quieren, podrían instalar un tubo en cada tanque de acido que
pasarian a traves de las ventanas para tener ventilacion hacia fuera de la
planta. Aunque no deberia ser necesario, instalar un tipo de ventilacion
sea buen idea.

2016-09-29 14:28 GMT-06:00 jonschristensen notifications@github.com:

**Comment by eak24** [comment]
Las tanques de acido ya instalado en la mesa de aislamiento. No tienen aislamiento entre los tanques y los otros.
